# Site settings
title: Road Less Traveled
email: roadlesstraveled@bu.edu
description: "The Road Less Traveled is a site dedicated to sharing stories of BU Alumni and the unique paths they take after graduation. To find out more about .... and .... and..... etc.."
baseurl: "/roadlesstraveled"
url: "http://smgserv1.bu.edu"

# Build settings
markdown: kramdown
permalink: pretty

# Custom settings
excerpt_separator: ""
